var annotated_dup =
[
    [ "HeightFunction", null, [
      [ "MyRaySceneQueryListener", "class_height_function_1_1_my_ray_scene_query_listener.html", null ]
    ] ],
    [ "KITF_Utils", null, [
      [ "MagixUtils", "class_k_i_t_f___utils_1_1_magix_utils.html", "class_k_i_t_f___utils_1_1_magix_utils" ]
    ] ],
    [ "ObfuscatedZip", null, [
      [ "FileNameCompare", "struct_obfuscated_zip_1_1_file_name_compare.html", null ],
      [ "ObfuscatedZip", "class_obfuscated_zip_1_1_obfuscated_zip.html", "class_obfuscated_zip_1_1_obfuscated_zip" ],
      [ "ObfuscatedZipDataStream", "class_obfuscated_zip_1_1_obfuscated_zip_data_stream.html", "class_obfuscated_zip_1_1_obfuscated_zip_data_stream" ],
      [ "ObfuscatedZipFactory", "class_obfuscated_zip_1_1_obfuscated_zip_factory.html", "class_obfuscated_zip_1_1_obfuscated_zip_factory" ]
    ] ],
    [ "AllocFlags", "struct_alloc_flags.html", null ],
    [ "Attack", "struct_attack.html", null ],
    [ "AttackFX", "struct_attack_f_x.html", null ],
    [ "ChannelInstance", "class_channel_instance.html", null ],
    [ "CollBox", "struct_coll_box.html", null ],
    [ "Collision", "struct_collision.html", null ],
    [ "CollSphere", "struct_coll_sphere.html", null ],
    [ "Critter", "struct_critter.html", null ],
    [ "CritterAttack", "struct_critter_attack.html", null ],
    [ "FileLocator", "class_file_locator.html", null ],
    [ "Gate", "struct_gate.html", null ],
    [ "HitInfo", "struct_hit_info.html", null ],
    [ "LoopedSound", "struct_looped_sound.html", null ],
    [ "MagixAlertBox", "class_magix_alert_box.html", null ],
    [ "MagixAnimated", "class_magix_animated.html", null ],
    [ "MagixApplication", "class_magix_application.html", "class_magix_application" ],
    [ "MagixCamera", "class_magix_camera.html", null ],
    [ "MagixCampaignManager", "class_magix_campaign_manager.html", "class_magix_campaign_manager" ],
    [ "MagixCharScreenManager", "class_magix_char_screen_manager.html", "class_magix_char_screen_manager" ],
    [ "MagixChatManager", "class_magix_chat_manager.html", null ],
    [ "MagixCollisionManager", "class_magix_collision_manager.html", null ],
    [ "MagixCritter", "class_magix_critter.html", null ],
    [ "MagixCritterManager", "class_magix_critter_manager.html", null ],
    [ "MagixEffectsManager", "class_magix_effects_manager.html", null ],
    [ "MagixExternalDefinitions", "class_magix_external_definitions.html", "class_magix_external_definitions" ],
    [ "MagixFrameListener", "class_magix_frame_listener.html", null ],
    [ "MagixGameStateManager", "class_magix_game_state_manager.html", null ],
    [ "MagixGUI", "class_magix_g_u_i.html", null ],
    [ "MagixHandler", "class_magix_handler.html", null ],
    [ "MagixIndexedUnit", "class_magix_indexed_unit.html", null ],
    [ "MagixInputManager", "class_magix_input_manager.html", null ],
    [ "MagixItem", "class_magix_item.html", null ],
    [ "MagixItemManager", "class_magix_item_manager.html", null ],
    [ "MagixLiving", "class_magix_living.html", null ],
    [ "MagixLoadingBar", "class_magix_loading_bar.html", "class_magix_loading_bar" ],
    [ "MagixMiniMap", "class_magix_mini_map.html", null ],
    [ "MagixNetworkManager", "class_magix_network_manager.html", null ],
    [ "MagixObject", "class_magix_object.html", null ],
    [ "MagixOwnershipManager", "class_magix_ownership_manager.html", null ],
    [ "MagixPlayer", "class_magix_player.html", null ],
    [ "MagixSkyManager", "class_magix_sky_manager.html", null ],
    [ "MagixSoundManager", "class_magix_sound_manager.html", null ],
    [ "MagixUnit", "class_magix_unit.html", null ],
    [ "MagixUnitManager", "class_magix_unit_manager.html", null ],
    [ "MagixWorld", "class_magix_world.html", null ],
    [ "MapChangeData", "struct_map_change_data.html", null ],
    [ "MovableTextOverlay", "class_movable_text_overlay.html", null ],
    [ "MovableTextOverlayAttributes", "class_movable_text_overlay_attributes.html", null ],
    [ "NetworkMessage", "struct_network_message.html", null ],
    [ "ogremagixApp", "classogremagix_app.html", "classogremagix_app" ],
    [ "ogremagixFrameListener", "classogremagix_frame_listener.html", null ],
    [ "PetFlags", "struct_pet_flags.html", null ],
    [ "PlayerData", "struct_player_data.html", null ],
    [ "Portal", "struct_portal.html", null ],
    [ "PositionInfo", "struct_position_info.html", null ],
    [ "RectLayoutManager", "class_rect_layout_manager.html", "class_rect_layout_manager" ],
    [ "ScriptedUnit", "struct_scripted_unit.html", null ],
    [ "Skill", "struct_skill.html", null ],
    [ "SoundInstance", "class_sound_instance.html", null ],
    [ "SoundManager", "class_sound_manager.html", null ],
    [ "TameData", "struct_tame_data.html", null ],
    [ "Wall", "struct_wall.html", null ],
    [ "WaterBox", "struct_water_box.html", null ],
    [ "WeatherEvent", "struct_weather_event.html", null ],
    [ "WorldCritter", "struct_world_critter.html", null ]
];